spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: java
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: darshan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
